import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';

import Link from 'next/link';
import { Home } from 'lucide-react';
import { ThemeProvider } from 'next-themes';

import { Button } from '@/components/ui/button';

import { ModeToggle } from './theme-toggle';

const geistSans = localFont({
  src: '../assets/fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: '../assets/fonts/GeistVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'Nextjs Playground',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans`}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <div className='fixed top-4 right-4 rounded-full z-50 flex items-center gap-2'>
            <Button asChild size={'icon'} variant={'outline'}>
              <Link href='/'>
                <Home />
              </Link>
            </Button>
            <ModeToggle />
          </div>

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
