import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';

import Link from 'next/link';
import { Home } from 'lucide-react';

import { Button } from '@/components/ui/button';

const geistSans = localFont({
  src: '../assets/fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: '../assets/fonts/GeistVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'Nextjs Playground',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans`}>
        <Button
          asChild
          className='fixed top-4 right-4 rounded-full z-50'
          size={'icon'}
          variant={'outline'}
        >
          <Link href='/'>
            <Home />
          </Link>
        </Button>
        {children}
      </body>
    </html>
  );
}
